### ISSUE TITLE
Might be able to provide a better dataset for CS:GO

### ISSUE THREAD

**Issue by sens0rer** [JaksyMarci/trueskill-plus#2]
I'm working on an up-to-date dataset of CS:GO matches for an ML project.
I've tested ~30k matches up to August 2019 with trueskill and the accuracy is ~60-65%.
I'm currently pulling only the scores, but I'm planning on getting all the useful data available on hltv.org. It will take some time, but when I'm done, I can share it with you if you're interested

**Comment by sens0rer** [comment]
Cool project btw!
It's nice to see someone finally implementing Trueskill 2

**Comment by JaksyMarci** [comment]
Thanks!
I wouldn't call this a complete (nor a good) implementation - i'm just using the ideas that were presented in the paper, with some own ideas and interpretations.
Although it proved to be just perfect for BSc thesis project, which I've already submitted. I no longer need the data, but the great folks at Kaggle.com (where i got the original one) would much appreciate it!
